[FEATURE] Added Sentry
ae-utbm/sith4 pull request #7
Opened 2022-10-03 21:38 UTC by Juknum

- Added Sentry support to the UI, but I can't figure out how to display the "what happened panel" when an error occurs
- You can find the reported issue [here on Sentry](https://ae2.utbm.fr/organizations/ae-info/projects/sith4/?project=4503921403297792)

## TODO: 
- [ ] Display the what happened panel
- [ ] Add tests for it?

2022-10-04 15:05 UTC, TheoDurr commented
En fait, l'objectif était de lier les crashs de l'api (erreurs 500) avec la popup du front. Et non pas lier le front au Sentry. 

Je me rends compte que les deux sont nécessaires mais les erreurs 500 de l'api sont bien plus critiques à mon sens.

2022-10-04 16:47 UTC, Juknum commented
Ahh oue carrément, on s'était mal compris mdrr

2022-10-10 08:08 UTC, TheoDurr requested changes

2022-10-10 08:08 UTC, TheoDurr commented on .env.example
> +VUE_APP_SENTRY_DSN=https://sentry.io/...
Normalement, lettre l'URL du DSN du projet API devrait les lier automatiquement

2023-01-13 14:06 UTC, closed without merging